name: Test

on:
  pull_request:
    branches:
    - develop
jobs:
  build:
    runs-on: ubuntu-lastest
    
    steps:
    - users: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: yarn
    - run: yarn test
      env:
        CI: true
